### ISSUE TITLE
No expand for editor on OSX

### ISSUE THREAD

**Issue by scroix** [museumsvictoria/nodel#101]
There doesn't appear to be an option to expand the editor on OSX. I've attempted across Chrome, Firefox and Safari.

![screen shot 2017-04-04 at 11 14 23 am](https://cloud.githubusercontent.com/assets/9277107/24638658/ab76bd1e-192d-11e7-833b-af132a36d95b.png)

**Comment by justparking** [comment]
@mcartmel tells me this might be fixed for OSX now - @scroix Can you confirm?

**Comment by scroix** [comment]
This one is long done and dusted -- *thank you.*
