### ISSUE TITLE
File management for binary assets

### ISSUE THREAD

**Issue by mcartmel** [museumsvictoria/nodel#106]
Following on from #90, need to also add support for managing binary assets.

**Comment by mcartmel** [comment]
It's still not possible to upload a binary file using the editor. This is becoming more relevant with the increased use of frontends, for example it's not straightforward to add a simple logo or background image.

**Comment by justparking** [comment]
As per #90, the backend should already supports binary assets.

Have you tried the curl example but with a binary file?

e.g. `> curl http://10.1.1.12:8085/nodes/MyFrontEnd/REST/files/save?path=content/myimage.png -v --data-binary @myimage.png`

**Comment by mcartmel** [comment]
Apologies, I just realised why I had separated out this issue now. Just need to create a method for file upload on the UI alongside the editor.

**Comment by justparking** [comment]
A drag and drop into the node would be awesome. Folder selection / creation would be an issue.

**Comment by mcartmel** [comment]
This is now supported in the new UI. If you drag a binary (or any) file over the top of the editor, the file will be uploaded and you will be prompted for the name/location.
