### ISSUE TITLE
rev319 not showing activity for many recipes

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel#108]
Rev319 is not showing activity for many types of nodes.  rev300 does seem to work.

Specifically WOL (older)
Pjlink (older and newest)
iboot 
adamio 6060 mk1
upd
brightsign

what is working
gallery
computer
exhibit

![image](https://cloud.githubusercontent.com/assets/3997916/25629405/3d8898fc-2f1e-11e7-8815-d3afdf9ae52f.png)

**Comment by justparking** [comment]
@scienceworld has confirmed latest release resolves this issue. Related commit 149dd192e54f915103e094c9066b64990953ec42.
