### ISSUE TITLE
Activity view string escaping failure

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#112]
I noticed this when feeding it raw XML, for example, it reports `<asdf/>` as a blank string (see screen shot below):

![image](https://cloud.githubusercontent.com/assets/5266533/26770794/10373d5a-49fd-11e7-8dcb-e81496450120.png)

This points to an escaping failure so potentially other content may fail, not just content that looks like XML.

**Comment by justparking** [comment]
Another example:

![image](https://user-images.githubusercontent.com/5266533/33160885-111f14ec-d074-11e7-8cc6-03b2d5919913.png)

**Comment by mcartmel** [comment]
Resolved
