### ISSUE TITLE
Status binding to self loopback overload

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel#114]
Created an exhibit node with members and bound member status and power to itself (same node) creating a loopback situation maxing out the host threadpool and cpu.  host was unresponsive until loop condition resolved.

**Comment by scroix** [comment]
Is this perhaps referring to a device node listening out for an event generated by it's associated group node? (The alternative behaviour to a remote action being called from an exhibit to a device node)

**Comment by scienceworld** [comment]
No, I accidentally bound the event power and status of the ExhibitGroup node to itself.  so its definately a loopback.  It was my accident, but still created a bad situation with the nodel host.
