### ISSUE TITLE
Linux Service: service fails to start after reboot (pid file folder missing)

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#117]
If the [Wiki instructions](https://github.com/museumsvictoria/nodel/wiki/Install-Nodel-as-a-serviced-%28Ubuntu-post-15.04%29-process) are followed, the service may not start after a reboot.

This is due to the PID folder being created on TMPFS.

Without defaulting to user root, a solution is required and instructions need to be updated.

**Comment by mcartmel** [comment]
Updated wiki instructions to use tmpfiles.d. Folder is now created on startup.
