### ISSUE TITLE
Add (node) from recipe markdown is escapable

### ISSUE THREAD

**Issue by scroix** [museumsvictoria/nodel#119]
I noticed markdown files are parsed to provided comments when selecting new nodes from exisiting local recipes, which is _great_.

It's minor, but I also noticed there isn't any protection against escaping through the markdown.

<img width="1094" alt="screen shot 2017-11-23 at 3 30 16 pm" src="https://user-images.githubusercontent.com/9277107/33156972-a2fd52a4-d063-11e7-8989-d8e2b4cce375.png">

The second example (walking here) is just a test, but the first example (disappearing status) is a legit readme.md provided for the Group recipe that happens to be formatted in such a way that causes this escape.

**Comment by justparking** [comment]
Have investigated this and believe there is data interference in the web ui, I reckon as a result of `<>` brackets.

For example, given this result of `/REST/recipes/list`:
```json
[
  {
    "path": "nodel-official-recipes/Group",
    "modified": "2018-03-15T14:04:04.000+11:00",
    "readme": "# Group Node\n\nA group node is designed to aggregate signals and (optionally) actions.\n\n## Actions\n\nActions ... <SNIP>up or dashboard ─┐\n    Status     ->   Disappearing Status -> Member Assumed Status -> Member Status   ->    Event wiring\n```\n"
  },
  {
    "path": "nodel-official-recipes/Other",
    "modified": "2018-03-15T14:04:04.000+11:00",
    "readme": "A little node!"
  }
]
```
The user-interface is presented with:
![image](https://user-images.githubusercontent.com/5266533/37459155-55533718-289b-11e8-91a0-12fd1d03634c.png)

**Comment by mcartmel** [comment]
Yes agreed. Needs basic escaping.

**Comment by mcartmel** [comment]
Fixed in latest commit.
