### ISSUE TITLE
Creation of bindings via REST API

### ISSUE THREAD

**Issue by mcartmel** [museumsvictoria/nodel#12]
Currently, a binding can only be declared by the node script. We need to add the ability to add an on-demand node binding using the REST API (for use by the UI).

**Comment by justparking** [comment]
Bindings can be created and adjusted on the fly using `create_remote_action` and `create_remote_event` toolkit functions.

If these are also needed via the REST API, simply expose a REST end-point using respective Actions that can be scripted to accommodate the application.
