### ISSUE TITLE
Front-End Building Blocks' shortcomings

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#124]
I was hoping to use the Yamaha Amp front-end as a good real-world example of what the front-end framework can do.

Some issues I've come across (see screenshot below):
* **(1)** `<link url='...'>` does not support any internal text so instead a massive title has to be used
* **(2a)** A light-weight "field name/ field value" UI element bound to an event/signal is not supported. Instead a very heavy `<panel>` has to be used.
    * in this example, it'd be nice to have those basic text fields presented elegantly (**Firmware**, **Run Mode**, **Device Error Status**
* **(3)** How do you layout a bank of range controls elegantly (spacing an issue; and an index label would be nice)?
* **(4)** `<range>` is missing the current value, a bit like how the meters have (shown)
* **(5)** How to you layout a bank of On/Off switches elegantly (an index label would be nice)?
* **(6)** `<meter>` only support 0-100. I'd say standardise on typical dB audio range of -60dB to +6dB.
* **(7)** Natively supporting a bump on `<range>` would be very useful. So **+** and **-** or **⇧** and **⇩**

I consider **(2)** a major shortcoming.

![untitled drawing 1](https://user-images.githubusercontent.com/5266533/36955724-43e03c44-207e-11e8-8c14-fb8da10586eb.png)

[(Link to original editable drawing)](https://docs.google.com/drawings/d/1yd9bj-gtmvqnKropuR0hAv5sWHjGXVcrMZYgdiE4am8/edit)

**Comment by justparking** [comment]
Hey @scroix, please feel free to make contributions based on how you've used them in the past.

**Comment by mcartmel** [comment]
Closing to reopen in the recipes repo.
