### ISSUE TITLE
error retrieving results + server stopping

### ISSUE THREAD

**Issue by rhulse** [museumsvictoria/nodel#133]
This is release v2.1.1-release330.

The main search screen on the master node (running on windows server) come up with the error 'error retrieving results', and the server appears to just stop responding to requests.

Trying to restart the service gets a windows Could Not stop the service 1053 error, and then seems to be stuck on 'stopping' forever in the services window.

Rebooting the machine fixes the problem, although it eventually stops. Adding some links to the dashboard screen and hitting save (which is very slow) causes it to start refusing connections right away.

**Comment by justparking** [comment]
Hi, there could be a rogue node that's consuming resources or at least not releasing them gracefully.

How long does it take to show these symptoms?

Can you check its logs at `/diagnostics.htm` on your host or a full dump at `/REST/logs?max=1000` in case of any "stuck functions" entries.

**Comment by rhulse** [comment]
Thanks. I manged to track this to some PC and interactive nodes (that spawn process containers) that had been staged on the server prior to being moved to the real hardware.  I moved them into a subfolder, and things seem to have stabilized.

**Comment by justparking** [comment]
OK, good to hear you've tracked it down.

FYI - there is work being done to have better partitioning of the thread-pools meaning the host will be protected from most misbehaving nodes and more importantly, be able to notify of the problem.

Closing this issue for now.

**Comment by rhulse** [comment]
Thanks!
