### ISSUE TITLE
unhandled ThreadPool exception causing freeze

### ISSUE THREAD

**Issue by rhulse** [museumsvictoria/nodel#134]
I am getting this on the diagnostics.html page, and they appear to causing nodel to become unresponsive. (I can't say for certain, but have exhausted other options.)

```
18-07-12 12:51:34 [pool_Dynamic nodes_21] [org.nodel.threading.ThreadPool] An unhandled exception occurred within a thread-pool
    java.lang.IllegalStateException: Timer already cancelled.
    	at java.util.Timer.sched(Unknown Source)
    	at java.util.Timer.schedule(Unknown Source)
    	at org.nodel.threading.Timers.schedule(Timers.java:105)
    	at org.nodel.jyhost.PyNode.monitorConfig(PyNode.java:501)
    	at org.nodel.jyhost.PyNode.access$700(PyNode.java:83)
    	at org.nodel.jyhost.PyNode$7.run(PyNode.java:505)
    	at org.nodel.threading.Timers$1.run(Timers.java:173)
    	at org.nodel.threading.ThreadPool.threadMain(ThreadPool.java:303)
    	at org.nodel.threading.ThreadPool.access$000(ThreadPool.java:26)
    	at org.nodel.threading.ThreadPool$1.run(ThreadPool.java:213)
    	at java.lang.Thread.run(Unknown Source)
```

Version:
- Running open-source build 2.1.1-release_r330 by Museum Victoria & Lumicom Pty Ltd
- Serving from TP137298, advertising http://10.5.11.2:8085/nodes/%NODE%/
- Uptime a minute (started 12-Jul-2018 12:27:10)
- Host path C:\AV\nodel\., nodes root C:\AV\nodel\.\nodes
- Hosting rule Include everything, exclude nothing
- Scripting toolkit reference
- Announcing agent nodel/2.1.1 java/1.8.0_141-b15 Oracle_Corporation Windows_Server_2016 arch64
- Build server was SENSELESS (built 8-Nov-2017 19:06:04 +13:00, last commit)

**Comment by rhulse** [comment]
Sometimes with 10 minutes, although I rebooted the PC as the I could not restart the service, and it seems to have run OK overnight, and I can see the graphs on `diagnostics.htm` updating. 

For some reason the Dashboard doesn't update now. There is definitely something making this install unstable.

I have downloaded process explorer and the instance is using 2393224 K of memory and 0.05% of CPU. I'll see if I can make it go unstable again.

**Comment by justparking** [comment]
It's actually the handle and thread counts I was after.

Avoiding what could be a longer conversation, I might take this off github-issues and catch you on Slack instead until we get to the bottom of it.

**Comment by justparking** [comment]
Belated update: turns out there was a rogue node that was exhausting CPU and memory.

**Comment by justparking** [comment]
Forgot to add, was the same issue as #114.

The newer thread-pooling architecture coming soon should prevent this condition and possibly warn of its existence.
