### ISSUE TITLE
Spacebar does not toggle checkboxes

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#144]
Prevents efficient use of the keyboard when doing heavy config.

e.g. shown in screenshot below, pressing spacebar does nothing when standard UI convention says it should toggle the check-state.

![image](https://user-images.githubusercontent.com/5266533/49501415-e68ccb80-f8c6-11e8-9182-688bca645ecd.png)

**Comment by mcartmel** [comment]
This is supported in the new UI, to be released

**Comment by mcartmel** [comment]
New UI released so closing this issue.
