### ISSUE TITLE
Other ways to navigate between nodes

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#145]
Right now the only way to jump between nodes is having to use the search page. Having additional direct mechanisms could be useful.

I propose that the bindings section be used for that purpose as it lists related nodes.

See screenshot below indicating where navigation links could be added:

![image](https://user-images.githubusercontent.com/5266533/49765015-333c3080-fd25-11e8-8174-65843f59bc40.png)

So clicking on those points (using conventional navigation symbols) takes you straight to the relevant node(s).

**Comment by scienceworld** [comment]
Prev/next based on last used filter
Search dialog in top right corner with ajax type search where you could search and click on the node without having to go back to the host page and starting your search over again.
Remembering your previous filter, not just your previous node when hitting back

**Comment by scroix** [comment]
One of our technicians pointed out there is no way to navigate to a frontend's `index.xml` without altering the URL directly.

**Comment by scienceworld** [comment]
Yes, that’s really annoying and prevents people from successfully using the dashboard.  It would also be nice to pin a Dashboard to the nodel header for quick and easy access.

**Comment by scroix** [comment]
I've been thinking about the three options suggested for navigation links. 

The proposal for hyperlinks inside signals (#146) sets a standard for embedding the navigation icon inside the text field. The only concern with doing that here is cluttering small view-ports.

![mini-bindings](https://user-images.githubusercontent.com/9277107/49914776-b2c52d80-fee6-11e8-9289-03ff53126fc6.PNG)

It's a minor issue, but the links being attached would also generate duplications when two bindings reference the same node.

**Comment by scroix** [comment]
@scienceworld has suggested a lot of good ideas for convenience updates to the UI. There are perhaps even _too many_ to fit into the existing design without introducing clutter. I want to float the idea of introducing drawers as another layer on the UI where some of these utilities could be present.

![drawer](https://user-images.githubusercontent.com/9277107/49915487-038a5580-feea-11e8-8455-0b6dbd8ed35d.gif)

**Comment by mcartmel** [comment]
A few of these suggestions have been included in the new UI, in particular:

- Nav to the 'frontend' page from top-right nav
- Search nodes from top-right nav
- Link from bindings to node, however on this one I have made it link to the node search page instead of the node directly as it added a unacceptable overhead to the UI to search for the node and test reach-ability for each wired binding. Hopefully this is a reasonable compromise for now.

Any feedback would be appreciated @scienceworld @justparking @scroix . Keeping this open for now.

**Comment by mcartmel** [comment]
Closing this issue as there has been no further feedback.
