### ISSUE TITLE
schedule effective date and expiry date

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel#15]
When scheduling into the future there are times when you might change seasonality and need to expire a schedule, and then set up a new schedule with a new effective date.

Specifically...

tuesday to friday we close at 5pm.  During Christmas and the Summer we close at 6pm.  We'd like to be able to schedule the normal 5pm closing of tuesday to friday closing at 5pm and then expire it on december 22nd.  On december 23rd onwards we'd like to be able to have a new schedule for tuesday to friday that closes at 6pm. 

We understand that there are exceptions, but if your exception is the norm not an exception we'd like to be able to shift from one schedule to another.  The only apparent method right now is to intervene on the morning of the 23rd and modify the schedule that's existing.  this opens up opportunities for human error or forgetting to change the schedule the day of.

Thanks

J

**Comment by mcartmel** [comment]
You might be interested to know that we have been contracted to develop a new scheduling recipe that pulls events from one or more Google Calendars. The details are still being finalised. If you have any ideas that you would like to throw into the mix then please let us know.

**Comment by scienceworld** [comment]
That would be spectacular.
We just implemented a similar project to do google calendar integration in our digital signage.

1) parameterize the url for the linked calendar
2) support having one google account with many calendars
3) parameterize google calendar polling period
4) have action button for “get current schedule” that grabs the schedule and displays in response to confirm next off and on events
5) support mute vs all on and all off events
6) support google calendar native functions (re-occurance, exceptions from re-occurance, delegation of calendar, etc)
7) potential to follow master calendar and if events in gallery specific calendar follow that one instead?

Thanks!


Wonder who’s contracting the enhancement?

On Oct 19, 2016, at 8:47 PM, mcartmel <notifications@github.com<mailto:notifications@github.com>> wrote:


You might be interested to know that we have been contracted to develop a new scheduling recipe that pulls events from one or more Google Calendars. The details are still being finalised. If you have any ideas that you would like to throw into the mix then please let us know.

**Comment by mcartmel** [comment]
New scheduler will be released shortly, so we'll be retiring the old scheduler recipe.
