### ISSUE TITLE
Setting bindings should make use of 'group' & 'title' for additional context

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#158]
Selecting from the event/action name list alone is not ideal in many situations.

This example shows how the Control Unit can only be found by referring to the original node (and "floating" over the signal/action).
![image](https://user-images.githubusercontent.com/5266533/70530089-34a57080-1ba6-11ea-9b68-a915069d89b0.png)

Here it shows it's impossible to know which item(s) relate to "Corridor":

![image](https://user-images.githubusercontent.com/5266533/70530169-63bbe200-1ba6-11ea-8b4e-f8f19fec9319.png)

Getting context from the Group and Title would significantly improve selecting things that handle anything that may have friendly names, say Presets, Inputs, Outputs, Addresses, etc.

**Comment by mcartmel** [comment]
@justparking just requesting some feedback to the latest commit.

**Comment by justparking** [comment]
(belated update) This has been a good update.
