### ISSUE TITLE
Use of Base64 encoded thumbnails makes regular frontend unusable but not Dashboard's

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#159]
For Dashboards that make use of even just a few Base64 encoded thumbnails as signal data, the frontend grinds to a halt and becomes unusable.

e.g. 
![image](https://user-images.githubusercontent.com/5266533/70530944-0aed4900-1ba8-11ea-966a-6f98384a45bc.png)

The size of the thumbnails is typically less than 20KB.

![image](https://user-images.githubusercontent.com/5266533/70531096-59024c80-1ba8-11ea-8cad-486f176889e8.png)

The Dashboards themselves have no problem whatsoever loading and consuming the equivalent data.

**Comment by justparking** [comment]
So the regular frontends struggle; the Dashboard frontends don't.

**Comment by mcartmel** [comment]
@justparking Can you please test the latest update and provide feedback?

**Comment by justparking** [comment]
I don't think this is an issue any more.
