### ISSUE TITLE
v2.2.1: all pop-up dialogues very keen to close and lose data

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#162]
see https://github.com/justparking/feature_nodeluiunify/issues/61

**Comment by mcartmel** [comment]
@justparking This is a default behaviour in Bootstrap that [others have problems with](https://github.com/twbs/bootstrap/issues/13816). I've added a workaround which I hope doesn't cause any side-effects (I haven't found any yet). Can you please test and provide feedback?

**Comment by justparking** [comment]
Seems better now.
