### ISSUE TITLE
Java differences cause error with nodel service

### ISSUE THREAD

**Issue by jordonrandall** [museumsvictoria/nodel#164]
When using adoptopenjdk we get the follow error when trying to run the service 

`[2019-12-16 21:51:25] [info]  [  540] Commons Daemon procrun (1.0.15.0 64-bit) started
[2019-12-16 21:51:25] [info]  [  540] Starting service 'NodelHostsvc' ...
[2019-12-16 21:51:27] [error] [  540] Failed to start 'NodelHostsvc' service
[2019-12-16 21:51:27] [error] [  540] The data area passed to a system call is too small.
[2019-12-16 21:51:27] [info]  [  540] Start service finished.`

if we uninstall OpenJDK8U-jre_x64_windows_hotspot_8u232b09 and install jre-8u231-windows-x64 the service starts correctly.

**Comment by jordonrandall** [comment]
I tested a few iterations and found out that by enabling the check marks to set the java home and use the oracle registry keys then the nodel service was able to start.

**Comment by mcartmel** [comment]
Hi @jordonrandall. Just checking if this requires any follow up? It seems from your last comment that you were able to resolve the issue.

**Comment by jordonrandall** [comment]
We got it going.  It was the java home variable had to be set
thanks

Jordon Randall
Director, IS and Technology
Jordon.Randall@ocean.org<mailto:Jordon.Randall@ocean.org>
D 604 659 3407
________________________________
Our vision is a world in which oceans
are healthy and flourishing. | ocean.org
[Facebook]<https://www.facebook.com/oceanwise>[Twitter]<https://twitter.com/oceanwise>[Instagram]<https://www.instagram.com/oceanwise/>[Youtube]<https://www.youtube.com/channel/UC0hLWXESQRctgaVPT-8N7Rw>[Snapchat]<https://www.snapchat.com/add/oceanwise>

[Ocean Wise Logo]<http://www.ocean.org/>

**Comment by justparking** [comment]
FYI, the service wrapper that Nodel uses (Apache Commons Daemon docs - [link](http://commons.apache.org/proper/commons-daemon/procrun.html)), supports many different ways to create a Java environment.

My preference is to use the `--jvm` option and specify the DLL entry-point and NOT perform a standard Java installation, rather use portable versions (simply pick version, download and extract zip into desired folder)

Here is a batch file that performs the service installation in one hit assuming the JDK has been downloaded and extracted.

```bat
rem User parameters

set SHORTROLE=main
set NODEL_JAR=nodelhost-release-2.1.1-rev389.jar
set JAVA_VERSION=jdk8u232-b09
set NODEL_HOME=H:\spotfornodel

rem Expected relative file structure, PREINSTALL state, by example:
rem   - H:\spotfornodel
rem   - H:\spotfornodel\bin\
rem   - H:\spotfornodel\bin\jdk___-b__\
rem   - H:\spotfornodel\bin\nodelhost-___-2._-rev.jar
rem   - H:\spotfornodel\service\NodelHostsvc.exe.x64
rem   - H:\spotfornodel\service\NodelHostsvcw.exe

rem The rest of these parameters are all derived from the user parameters above:

rem The short name of the Windows service (e.g. "nodel-main")
set NAME=nodel-%SHORTROLE%

rem The title / display name part e.g. "Nodel Host (main)"
set TITLE=Nodel Host (%SHORTROLE%)

rem The description part
set DESC=The Nodel project.

rem For nodel, Java and third-party binaries
set BIN=%NODEL_HOME%\bin

rem The full path to the Nodel JAR
set NODEL_JAR_PATH=%BIN%\%NODEL_JAR%

rem The Java home
set JAVA_HOME=%BIN%\%JAVA_VERSION%

rem The Java DLL entry-point used by the service
set JAVA_DLL=%JAVA_HOME%\jre\bin\server\jvm.dll

rem The file name of the service executable
set SVCNAME=%NAME%svc.exe
set SVC_PATH=%NODEL_HOME%\%SVCNAME%

rem The file name of the service controller user-interface
set SVCGUI=%NAME%svcw.exe
set SVCGUI_PATH=%NODEL_HOME%\%SVCGUI%

rem     (makes a copy of the process executable so that it can be spotted easily in process lists)
copy %NODEL_HOME%\service\NodelHostsvc.exe.x64 %SVC_PATH%
copy %NODEL_HOME%\service\NodelHostsvcw.exe %SVCGUI_PATH%

rem     (install the service)
%SVC_PATH% //IS --DisplayName "%TITLE%" --Description "%DESC%" --Startup auto --Jvm %JAVA_DLL% --StartMode jvm --StartClass org.nodel.nodelhost.Service --StartMethod start --StopMode jvm --StopClass org.nodel.nodelhost.Service --StopMethod stop --LogPath .\logs --Classpath %NODEL_JAR_PATH%

rem     (run the configurator to allow user to check preferences or just start the service immediately)
%SVCGUI_PATH%

rem     (to delete the service)
rem ..\%NAME%svc.exe //DS
```

When expanded, example command might look like this (manually line wrapped)
```bat
H:\mynodel\nodel-mainsvc.exe //IS --DisplayName "Nodel Host (main)" 
   --Description "The Nodel project." 
   --Jvm H:\mynodel\bin\jdk8u232-b09\jre\bin\server\jvm.dll 
   --Startup auto 
   --StartMode jvm 
   --StartClass org.nodel.nodelhost.Service 
   --StartMethod start 
   --StopMode jvm 
   --StopClass org.nodel.nodelhost.Service 
   --StopMethod stop 
   --LogPath .\logs 
   --Classpath H:\mynodel\bin\nodelhost-release-2.1.1-rev389.jar
```

Which corresponds to this service control GUI:
![image](https://user-images.githubusercontent.com/5266533/74203158-bc9d1900-4cc2-11ea-9282-fca63513b327.png)

I'll be added this to the Installation wiki pages soon.
