### ISSUE TITLE
Single use attribute for same 'event' 'action' attributes

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#165]
By example, it'd be nice if this:
```xml
<partialswitch action='MM2.08-PC Power' event='MM2.08-PC Power'/>
```
...could be written as:
```xml
<partialswitch join='MM2.08-PC Power'/>
```

(the word `join` came up in previous discussions as most appropriate. Other proposals included `actionevent`, `target`, etc.)

**Comment by mcartmel** [comment]
Added in commit https://github.com/museumsvictoria/nodel/commit/67892e557417eef6289669c5deb3ba927e21efca
