### ISSUE TITLE
Copy-and-paste from code-to-console or console-to-console often fails

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#178]
A very frustrating thing in the overhauled UI - when you copy and paste text from the console or the code section back into the console, the operation usually fails because of hidden characters, as shown in this example:

```log
> print param_ipAddress
05-08 13:21:05.49 exec - SyntaxError: ("no viable alternative at character '\xa0'", ('<string>', 1, 5, 'print\xa0param_ipAddress\n'))
05-08 13:21:05.49 
```

This is very easy to reproduce. Simply create a blank node, view the code, copy and paste any variable, say `param_disable`, along with `print <space>` into the console and press Enter.

I was using Chrome on Windows. I'm unsure if other browser/OS combinations are affected.

**Comment by mcartmel** [comment]
Can you please check that fix?

**Comment by justparking** [comment]
Confirmed fixed.
