### ISSUE TITLE
Nodel FQDN

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel#18]
We are using a VPN which only tunnels fully qualified domain names, and not just simple ipv4 dotted quad addresses.

Is there a way to make nodel use hostnames instead of ip addresses when linking to nodes?

eg when I go to our nodel server I go to http://nodel.xxxxxx.xxx  Nodel lists all the nodes and each node is hyperlinked.  when I click on a node my host url changes from the fqdn above, to the ip address of the nodel machine and the path to the node such as http://10.0.3.5/sometingnode.  

I have other ways to get to the host, but would be nice if the links used the hostname we came to the nodel site on, instead of changing it to the dotted quad address of the machine.

Thanks

**Comment by justparking** [comment]
Long standing issue update: The latest versions of nodel now offer a "Locals" view where only nodes local to the server you're browser are shown.

Hopefully this addresses your issue.
