### ISSUE TITLE
Adjustable fields not closest to relevant titles

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#180]
Shown here, the check boxes are closer to their neighbours than their related titles.

![image](https://user-images.githubusercontent.com/5266533/83747160-92250080-a6a3-11ea-8399-e37f5c1f9d8c.png)

e.g. Answering "Provides Status?" in the screenshot, it'd be understandable if the user checked the wrong box.

**Comment by mcartmel** [comment]
Addressed in f750b9a. Please feel free to open again if this styling causes any problems.
