### ISSUE TITLE
Frontend: Ctrl-C unnecessarily triggers autofill dialogue when updating bindings

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#184]
Configuring bindings can be very keyboard and mouse intensive. Popping up the autofill dialogue is very inconvenient and can easily lead to bad data being entered into the forms.

Example shown here when Ctrl-C is used:
![image](https://user-images.githubusercontent.com/5266533/84967007-533c8380-b156-11ea-8114-e25158abbc11.png)

**Comment by mcartmel** [comment]
Fixed in f750b9a
