### ISSUE TITLE
Frontend: lost support for sliders

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#185]
Previously this resulted in a slider:
``` py
@local_action({ 'group': 'Volume', 'schema': { 'title': 'Drag slider to adjust level', 'type': 'integer', 'format': 'range', 'min': 0, 'max': 100 }})
def Volume(arg):
  console.info('vol: %s' % arg)
```

Not any more:
![image](https://user-images.githubusercontent.com/5266533/85205195-19899980-b35d-11ea-8206-1e000af81504.png)

**Comment by mcartmel** [comment]
Fixed in f750b9a

**Comment by justparking** [comment]
`"type": "integer"` is not respected. Example shows messiness as arbitrary high number of decimal places is used (even if `number` was used).

![image](https://user-images.githubusercontent.com/5266533/91017849-1a2afe80-e632-11ea-85fd-40a5ba1fda65.png)

@mcartmel , schema was:
```js
{ 'type': 'integer', 'format': 'range', 'min': 1, 'max': 24 } }
```

**Comment by mcartmel** [comment]
Updated so that `"type":"integer"` will now apply a default step value of 1. It can be overridden by specifying a step value.

```
{ 'type': 'integer', 'format': 'range', 'min': 1, 'max': 24, 'step', 5 } }
```
