### ISSUE TITLE
"Open in new-tab" completely hobbled for Nav. -> Select UI (right-click and Ctrl-click) 

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#195]
It's not possible to use the standard browser operation "Open in new tab" (or window) when browsing an alternative UI (**Nav.** -> **Select UI** operation). It's a real pain to have to copy and paste URLs for no good reason.

It's quite common to have the technical Nodel interface open and want to open the alternate UI side-by-side. Normally a user would simply open up a new tab / window (using right click or Ctrl click) however that funcitonality has been completely disabled so the only outcome is replacing the open tab with the new interface.

![image](https://user-images.githubusercontent.com/5266533/98623664-508a3700-2360-11eb-86ad-fbf76770b399.png)

**Comment by mcartmel** [comment]
Changed from a native select to a Bootstrap dropdown menu so that anchor links can be used. CTRL key now works as expected.
