### ISSUE TITLE
Url link on frontend and dashboard nodes

### ISSUE THREAD

**Issue by paxofsnax** [museumsvictoria/nodel#197]
Not sure if this issue should be on the nodel recipe git but a simple link on frontend/dashboard recipes to the .xml (frontend, index) would be super helpful I seem to do this at least 10 times a day when working on implementation of nodel projects, before I save a bookmark.

**Comment by scroix** [comment]
It looks like you can switch from **Node-to-Frontend** pretty easily on 2.2.1.

![image](https://user-images.githubusercontent.com/9277107/104242692-a0e25a00-54b3-11eb-8b1d-0ab89f1b3e59.png)

But aside from your browser's "back" button. I don't think there is anything baked into the Frontend to switch back (**Frontend-to-Node**). Perhaps a button, or similar widget in the top-right corner (same position as Node UI) would be appropriate.

![image](https://user-images.githubusercontent.com/9277107/104245061-b0fc3880-54b7-11eb-9fc4-7af0589d001a.png)

**Comment by paxofsnax** [comment]
oh that's perfect. this is super handy when using an iPad/tablet to access nodel while doing daily checks.

**Comment by paxofsnax** [comment]
not usually going back but in a quick test - back button and swipe back, in safari goes back to nodel.xml
