### ISSUE TITLE
Opt-out multihomed operation

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#2]
The current network discovery system binds only to a single IP interface. If multiple interfaces are detected Nodel will insist one is explicitly chosen so as to keep multicasting simple and reliable. In those environments, ideally it should run regardless and function on all interfaces but with the option to opt-out, but still functioning in a safe, reliable and efficient manner.

**Comment by scienceworld** [comment]
I second the need for this.  Would solve our vlan migration problem where we want to move devices/exhibits from Vlan A to Vlan B.  The main nodel "server" would be multi-homed allowing for concurrent communication to nodes on both subnets.

**Comment by justparking** [comment]
This issue should not be relevant anymore as the latest release (https://github.com/museumsvictoria/nodel/releases/tag/v2.1.1-release246) supports automatic interface binding for multihomed hosts. See release notes for more information.

@scienceworld if this issue still affect you, please try the latest release to confirm whether multi-subnet support works for you and note against this issue.

Otherwise closing issue.

**Comment by scienceworld** [comment]
Installed today, has discovered hosts on other subnet.  Will keep it running and see how that goes including migrating some hosts to the new subnet.  Thank you for this.
