### ISSUE TITLE
Local-only node browser navigation page

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#214]
Currently this navigation path exists:
 1. node interface (`$NODE/index.xml`) ⟶
 2. global node browser (`/nodes.xml`) ⟶
 3. local server diagnostics (`/diagnostics.xml`)

Sometimes it can be useful to know exactly what's running on the server you're browsing i.e. local-only nodes. Besides that, sometimes the server is accessed from restricted locations that prevent the entire global list of nodes from being directly browsed and having a local-only list makes it clear and convenient what can be accessed.

To achieve that, I propose another step is added to the navigation path (see step 2. below)
 1. node interface (`$NODE/index.xml`) ⟶
 2. 🟢local node browser (`/locals.xml`) ⟶🟢
 3. global node browser (`/nodes.xml`) ⟶
 4. server diagnostics (`/diagnostics.xml`)

For **local node browser**, only nodes hosted on the current webserver will be shown and relative paths will be used instead of the absolute path the global browser currently provides.

(@mcartmel @scroix @paxofsnax and others - feedback welcome!)

**Comment by scroix** [comment]
The simple feedback is **yes, this is a great idea.** If I'm working on a network with multiple active node-hosts, I often find myself launching with the `--interface lo` flag to achieve a similar result.

When I start to think about it. There's a few questions that arise, such as:
- How does one _know_ to navigate to `/locals.xml`. This also applies to other commonly used pages (https://github.com/museumsvictoria/nodel/issues/202).
- Is this best achieved through the use of an additional page, or could `index.xml` include a filter for node-hosts? They're already differentiated by distinct icons.

**Comment by justparking** [comment]
Release notes are:

* feature #214: local-only browsing and navigation update:
   * local host (self) browsing now default
   * nodel icon to always browse nodel network
   * dynamic host icon to always browse local host (self) only
