### ISSUE TITLE
`required` schema flag not respected by web user-interface

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#215]
In previous versions of Nodel (<=v2.1) this flag was supported when saving parameters or calling Actions. Now it's not.

Shown by example:
```python
param_SpecialSetting = Parameter({ 'schema': { 'type': 'object', 'properties': {
  'name': { 'type': 'string', 'required': True, 'order': 1} ,
  'label': { 'type': 'string', 'order': 2 }
}}})
```

Old:
![image](https://user-images.githubusercontent.com/5266533/119094288-312d3e80-ba54-11eb-9b41-38ffe1688cfb.png)

Current:
![image](https://user-images.githubusercontent.com/5266533/119094314-39857980-ba54-11eb-9543-8b1343e3ddc3.png)

(@mcartmel FYI)

**Comment by scroix** [comment]
I think this is a duplicate (https://github.com/museumsvictoria/nodel/issues/207) but you've articulated it better!
