### ISSUE TITLE
`<meter>` control intialises to full reading

### ISSUE THREAD

**Issue by mmiller3016** [museumsvictoria/nodel#219]
When frontend is first viewed, meter shows up as full reading, despite being silent (-128dB) as shown below.

<img width="134" alt="Screen Shot 2021-10-06 at 1 25 18 pm" src="https://user-images.githubusercontent.com/92003958/136130990-50716f89-5d9f-4375-a123-c69243a57d80.png">
<img width="278" alt="Screen Shot 2021-10-06 at 1 26 27 pm" src="https://user-images.githubusercontent.com/92003958/136131085-fa31d0ab-fbd5-4e2e-930f-9a6d1ed053ab.png">

**Comment by justparking** [comment]
This was really difficult to reproduce. Eventually I figured out it was related to showing and hidden items dynamically using `showevent` like this, by example:

```xml
    <column sm='3' showevent='ShowMe'>
      <title>Speakers</title>
      <meter event='My Meter' range='db' type='horizontal' />
    </column>
```

FYI - @mcartmel
