### ISSUE TITLE
`<lighting>` element does not coerce argument types

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#225]
**Narrow to wider**, e.g. given...
```xml
<lighting event='Fixure1' options='rgbkwaui'/>
```
...should allow for this, but doesn't:
```python
lookup_local_event('Fixure1').emit('rgb(50, 50, 50)')
```

**HSx to RGB**, e.g. given...
```xml
<lighting event='Fixure1' options='rgb'/>
```
...should allow for this, but doesn't:
```python
lookup_local_event('Fixure1').emit('hsb(0, 20, 20')
```

**HTML-RGB to RGB**, e.g. given...
```xml
<lighting event='Fixure1' options='rgb'/>
```
...should allow for this, but doesn't:
```python
lookup_local_event('Fixure1').emit('#ff00ff')
```

Missing channels should be left undefined / unused i.e. not applied.

(refer to [lighting-front-end-element](https://github.com/museumsvictoria/nodel/wiki/lighting-front-end-element) wiki article)

**Comment by morimoriysmoon** [comment]
fixed fb348993472a17af4a347c983dab0b2eb6400be4
