### ISSUE TITLE
Frontend: Dynamic button array 

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#252]
Currently there is a `<dynamicselect>`  component that allows for a dynamic list of options that are presented via a pop-up.

In some cases it would be ideal to provide a list of buttons and no pop-up.

For the record, `<dynamicselect>` sample is listed as this:

```xml
<dynamicselect class="btn-default" data="DynamicList" join="Dynamic" />
```

As per `<dynamicselect>` it needs to support two-way binding (control and feedback).

**Comment by morimoriysmoon** [comment]
A new branch added.
https://github.com/automaticau/autonodel/tree/feat-dynamic-button-list

A new element is called 'dynamicselectbuttons'.
![image](https://user-images.githubusercontent.com/1762090/178195379-298ef09d-0bc6-4fea-9b5e-b525981ea806.png)

**Comment by justparking** [comment]
This was supposed to be in a separate fork but accidentally ended up in this repository:
https://github.com/museumsvictoria/nodel/tree/feat-dynamic-button-list

I'm going to kick off a pull request. Please review @mcartmel.

**Comment by morimoriysmoon** [comment]
@justparking @mcartmel 
The code moved to forked repository below.
https://github.com/morimoriysmoon/nodel/tree/feat-dynamic-buttons
Please review.
- data is compatible with <dynamicselect /> : E.g.> [ {key:, value:}...]
- no custom CSS added
- support confirm dialog

**Comment by justparking** [comment]
Nice one. This seems to work (*) for me. I tested it using this set up:

**index.xml**
```xml
<row>
  <column sm="6">
    <dynamicselect class="btn-default" data="DynamicList" join="Dynamic"/>
  </column>
  <column sm="6">
    <dynamicselectbuttons class="btn-default" data="DynamicList" join="Dynamic"/>
  </column>
</row>
```

**script.py**
```py
local_event_DynamicList = LocalEvent()

local_event_Dynamic = LocalEvent({ 'schema': { 'type': 'string' }})

@local_action({})
def Dynamic(arg):
  console.info('dynamic: %s' % arg)
  local_event_Dynamic.emit(arg)

def main():
    local_event_DynamicList.emit([ { 'key': 'a', 'value': 'JP'} ,
                                   { 'key': 'b', 'value': 'AM'} ,
                                   { 'key': 'c', 'value': 'JG'} ,
                                   { 'key': 'd', 'value': 'NP'} ])
```

Result:
![image](https://user-images.githubusercontent.com/5266533/179204340-d482ffaa-3849-4939-85d6-530a4f34d45e.png)


I'll create a pull request for review... although it does need to be added to the example XML first, @morimoriysmoon. Can you do that.

(*) when I used numerical values as keys it did a weird thing which I'll create another issue about.
