### ISSUE TITLE
Dynamic lists with numerical keys behave strangely 

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#255]
Refer to full sample listed in #253 - if this is data is used instead:

Part of **script.py**
```py
def main():
  local_event_DynamicList.emit([ { 'key': '1234', 'value': 'JP'} ,
                                 { 'key': '1235', 'value': 'AM'} ,
                                 { 'key': '1232', 'value': 'JG'} ,
                                 { 'key': '1212', 'value': 'NP'} ])
```

This is the very odd result:
![image](https://user-images.githubusercontent.com/5266533/179206295-d1c937e7-81a0-452a-b5d5-9c4055fcaedd.png)

And I'm not sure if `<dynamicselect>` would be affected by this kind of data too and we've just never come across it.

(@mcartmel FYI)

**Comment by morimoriysmoon** [comment]
Bug fixed to properly support 'number' type of arg (#254).
morimoriysmoon@91230b426ec2ff8ceddfb706a0eeb4084cde3d48

Does 'dynamicselectbuttons' need to support 'boolean' type of arg? Please advise me.

**Comment by justparking** [comment]
We'll leave as is.
