### ISSUE TITLE
Dynamic Button List selection on mobile doesn't work, on desktop does 

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#260]
As per title, using a mobile doesn't seem to to work. But on the desktop it does of course.

The block flickers but nothing happens.

**Comment by morimoriysmoon** [comment]
@justparking 
Dynamic elements depends on websocket to create children elements. 
I think you do not use "unify-websocket" branch for testing.
I confirm with "unify-websocket" merged, it works on mobile browser.

**Comment by justparking** [comment]
It is using unify-socket.

But I've just checked and it seems to be working.

You can see it here:
https://cfcfooty-rack1.http.lumicom.online/nodes/CFCFootyMeetingRoom2Frontend

Argh.

Ok, I'll close this issue.

Only outstanding thing is styling, and how that's supposed to be done.

Perhaps only CSS is all that's needed?
