### ISSUE TITLE
`<row>` does not respect "showevent" attribute

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#282]
Sometimes it's must better to be able to hide and show row elements. I'm hoping this can be done the same way it can be done with <column>.

**Comment by justparking** [comment]
I'm also hoping that this applies to `<row>` elements nested in `<table>`, not just in broader <row>/<column> scope.

Here's a made up example:
```xml
            <grid>
              <row showevent="ShowHeader">
                <cell>HEADER A</cell>
                <cell>HEADER B</cell>
              </row>
              <row>
                <cell>Data 1</cell>
                <cell>Data 2</cell>
              </row>
            </grid>
```

**Comment by morimoriysmoon** [comment]
A new branch added.
https://github.com/morimoriysmoon/nodel/tree/feat-row-respect-showevent

**Comment by justparking** [comment]
@morimoriysmoon - can you confirm this supports the "showvalue" attribute behaviour too?

**Comment by morimoriysmoon** [comment]
The attribute added.
morimoriysmoon@d83802ed3e1b311928bb8a325ff0408dde8445b0

**Comment by justparking** [comment]
@morimoriysmoon 

This update does not seem to affect `<row>` elements when they're nested in `<grid>` elements, as per my comment in this thread - https://github.com/museumsvictoria/nodel/issues/282#issuecomment-1432677894

**Comment by morimoriysmoon** [comment]
@justparking Oh sorry! I never thought <row> inside <grid> is handled in a different way.
A new branch added 9fd6620a2bf0c5cee81a32393a6f8f6ede03e138@morimori
