### ISSUE TITLE
Preventing extreme jumps with <range> by adjusting with handle only

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#286]
As mentioned in #285 , hitting the slider arbitrarily can result in extreme range jumps (and if "wired" to audio equipment, extreme jumps in volume).

To get around this I propose the <range> control ONLY allows adjustment when the slider handle itself is "gripped", as opposed being able to click anywhere on the slider.

I'm not sure if anyone can think of any side-effects of this behaviour?

Note, #285 will depend on this issue being resolved.

(@mcartmel @scroix @dargs FYI)

**Comment by morimoriysmoon** [comment]
A new branch added.
https://github.com/morimoriysmoon/nodel/tree/feat-improve-input-range

**Comment by justparking** [comment]
Added in f5d414276d4dcfc3f537703322043685598a83d0

**Comment by justparking** [comment]
@morimoriysmoon - just checking if you have the bugfix for this feature that related to double actions?

**Comment by morimoriysmoon** [comment]
@justparking Yeah. I added a new branch.
https://github.com/morimoriysmoon/nodel/tree/bugfix-range-nudge

**Comment by justparking** [comment]
Covered in commit 1215270dd0847f121f892c8f47958ad11f15a348
