### ISSUE TITLE
Activity Log does not load, causes browser fault

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#302]
With latest build I'm getting this error for some nodes in browser console:

![image](https://github.com/museumsvictoria/nodel/assets/5266533/d96ab89d-9e75-4093-9a05-cc6e97817842)

![image](https://github.com/museumsvictoria/nodel/assets/5266533/a6ff69e3-164f-4d0c-800d-7424aba18ff4)

(@mcartmel FYI)

**Comment by morimoriysmoon** [comment]
@mcartmel @justparking I think the text ```cummulative latency: 1775ms, histogram: <5ms 97, <20ms 2, <5s 1]``` makes JsViews confused. It is okay with ```cummulative latency: 1775ms, histogram: less than 5ms 97, less than 20ms 2, less than 5s 1]```

**Comment by justparking** [comment]
So it appears as though there is a string escaping issue, or lack thereof since I've proven it affects all versions of Nodel.

The key character is the `>`.

I'm going to cancel this issue and open a new one.
