### ISSUE TITLE
Remote bindings missing when spaces (*) involved

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#53]
_(*) could be more than just spaces._

As shown below, 

Given the raw data below (see screenshot):
![image](https://cloud.githubusercontent.com/assets/5266533/14516261/8801219a-0244-11e6-8188-2b119813ca4c.png)

The web user interface has a problem rendering the data (see below). Notice the blanks when there is supposed to be data. I believe it's related to spaces in the names of the remote events/actions.

![image](https://cloud.githubusercontent.com/assets/5266533/14516239/48f3b36e-0244-11e6-8019-11a26fee67eb.png)

And when I remove the spaces, it all works as it should.

**Comment by mcartmel** [comment]
I'm having trouble replicating this. Spaces seem to work ok for me. Can you set up something to show the problem?

**Comment by justparking** [comment]
I haven't been able to reproduce this anymore. Closing.

**Comment by scroix** [comment]
This issue still persists.

The bindings exist in the `nodeConfig.json` and, they appear wired, and they function.

However, they don't actually render in the UI.

![screenshot from 2018-03-15 08-32-25](https://user-images.githubusercontent.com/9277107/37433487-3d076104-2830-11e8-9275-e0792c650bf8.png)

I isolated the node to a new host, and the behavior persisted. I've packaged this up for perusal.

Interestingly... If you **delete** all the bindings (for some reason the in-line editor doesn't work in this case) all the bindings reappear, despite the file missing the bindings.

![screenshot from 2018-03-15 09-05-16](https://user-images.githubusercontent.com/9277107/37433627-bf2a234c-2830-11e8-9108-767764a113c4.png)

[example_unrendered.zip](https://github.com/museumsvictoria/nodel/files/1813284/example_unrendered.zip)

**Comment by justparking** [comment]
Have managed to reproduce using your example.

@mcartmel Will leave example running.

**Comment by mcartmel** [comment]
Just have a moment to look over this issue. 

I note that the name of the binding is:
`Member MM-MT Media Films Status`
But in the nodeConfig.json, the name of the binding is (note the extra spaces around the hyphen):
`Member MM - MT Media Films Status`

The binding will work because those spaces are ignored, but the UI will see them as being different; If you remove the spaces around the hyphen then it renders correctly. I'll see if I can make the UI ignore differences like this.
