### ISSUE TITLE
Several natural keyboard shortcuts are hobbled

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#63]
The following are disabled:
- **Ctrl-A** (select all) in the Parameters, Bindings (Events and Actions) sections
- **Up**, **Down** and _select_ when node name and node action/event autofill pop up occurs in remote bindings

Both of these can make mass updates very error prone and tedious as it requires constant switching between mouse and keyboard.

**Comment by mcartmel** [comment]
Added keyboard handlers for the autocomplete popups. CTRL-A should already be working.

**Comment by justparking** [comment]
Aaargh... keyboard cut-n-paste is hobbled. In fact it's the Ctrl key so a lot of shortcuts are broken 👎

**Comment by justparking** [comment]
And shift!!!

**Comment by mcartmel** [comment]
Yes, these keys were being prevented from use unnecessarily. Resolved now.
