### ISSUE TITLE
Graceful handling of titles for complex action/event declarations

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#66]
Declaration of non-simple actions/events is a particularly onerous task that could be alleviated if some simple safe defaults can be presumed.

Currently, this (legitimate) declaration...

``` python
local_event_MyEvent = LocalEvent({'schema': {'type': 'object', 'properties': {
        'myProperty1': {'type': 'string'},
        'myProperty2': {'type': 'string'}}}})
```

...leads to this misleading user-interface representation:
![image](https://cloud.githubusercontent.com/assets/5266533/19210062/e6efe8e4-8d63-11e6-9556-3e044655cec3.png)

The "undefined" bug aside, normally, without any explicit title-overrides, the UI generates graceful versions using event/action names e.g. **MyEvent** is used as a title despite it not explicity being declared via `... = LocalEvent({'title': 'My Special Event', 'schema': {'type': ...```

In the same way,  it should treat the above example like this:
![image](https://cloud.githubusercontent.com/assets/5266533/19210077/3e3c1ac8-8d64-11e6-8758-08f250343ead.png)

or for a cleaner look, this:
![image](https://cloud.githubusercontent.com/assets/5266533/19210082/588e452c-8d64-11e6-88f5-44ee0aa2fc80.png)

or this space-conscious version which is especially great when several array elements are involved:
![image](https://cloud.githubusercontent.com/assets/5266533/19210220/d6f48892-8d67-11e6-88a1-435b15220a40.png)

The equivalent (onerous) code being:

``` python
local_event_MyEvent2 = LocalEvent({'schema': {'type': 'object', 'title': 'Properties', 'properties': {
        'myProperty1': {'title': 'myProperty1', 'type': 'string'},
        'myProperty2': {'title': 'myProperty2', 'type': 'string'}}}})
```

this:

``` python
local_event_MyEvent3 = LocalEvent({'schema': {'type': 'object', 'title': '...', 'properties': {
        'myProperty1': {'title': 'myProperty1', 'type': 'string'},
        'myProperty2': {'title': 'myProperty2', 'type': 'string'}}}})
```

and this:

``` python
local_event_MyEvent3 = LocalEvent({'schema': {'type': 'object', 'title': '', 'properties': {
        'myProperty1': {'title': 'myProperty1', 'type': 'string'},
        'myProperty2': {'title': 'myProperty2', 'type': 'string'}}}})
```

**Comment by mcartmel** [comment]
Title now defaults to the key, which in the case of an event is 'arg'. A title is 'required' because there needs to be a block to click on to expand the section.

**Comment by justparking** [comment]
This isn't a good improvement. The way it now defaults to "___ properties" everywhere is not very elegant when you consider most of the time simple types are in use, not complex ones that have bundles of actual properties (see example below). If you can't make it using a clean name as the title, it's better off being blank than using the misleading "... properties" suffix.

This example shows how you've made it even more of a burden to define the metadata when simple types or in use:

```python
local_event_ShowDebug = LocalEvent({'title': 'Show debug logging?', 'order': 9998, 'group': 'Debug', 'schema': {'type': 'boolean'}})
```
Causes this:

![image](https://cloud.githubusercontent.com/assets/5266533/20646457/ddc5282a-b4cc-11e6-8a9d-8ebaec782a67.png)

The big +'s and -'s are clearly a great improvement and should be kept, but I think it'd be fine if you revert to its previous behaviour regarding titles and instead of "undefined" you use gracefully make it blank. That way everything still stays succinct but doesn't look like a bug.

**Comment by mcartmel** [comment]
I've simply removed the 'properties' word for now. Investigating other options to make it a bit more streamlined.

**Comment by mcartmel** [comment]
Committed a new fix for this issue to **feature_uimods** branch, for testing before releasing to the wild. 

Root elements are no longer automatically titled (they will be completely blank), but any child elements of a root object are auto titled. Also tweaked the CSS to handle blank titles.

Please feel free to reopen the issue if there are any problems with this fix.
