### ISSUE TITLE
Server disconnection indicator

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#71]
When a nodel host is unreachable (network change, reboot, etc.) there is no visual indicator to the user it is offline.

This applies to the Node, the Node browser and /diagnostics pages.

**Comment by mcartmel** [comment]
Applied an offline status indicator to the Node page

**Comment by justparking** [comment]
Would be nice on browse page too especially since "error retrieving results" could be misleading (see below).

![image](https://cloud.githubusercontent.com/assets/5266533/25878860/3e7000ee-3571-11e7-9757-2a249cf07dce.png)

**Comment by mcartmel** [comment]
Resolved in the new UI. All pages will show an offline message if Nodel cannot be contacted.
