### ISSUE TITLE
rev214 Events Editing Disabled

### ISSUE THREAD

**Issue by scroix** [museumsvictoria/nodel#72]
I noticed that I have been unable to edit any bindings (events/actions) in the latest revision 214.

I attempted to restart the service, but this didn't alleviate the problem.

I reverted back to revision 196 and the problem was resolved.

**Comment by scroix** [comment]
![screen shot 2016-11-24 at 9 59 07 am](https://cloud.githubusercontent.com/assets/9277107/20581395/a8fdf6a0-b22c-11e6-93a6-b3af885ef123.png)

To be more specific, I can't enter text in any of these fields - similar behaviour to if there was some sort of field validation exisiting, similar to if you define a parameter as numeric.

**Comment by mcartmel** [comment]
This was related to the new keyboard selection functions. Resolved.
