### ISSUE TITLE
Keyboard Shortcuts dev219

### ISSUE THREAD

**Issue by scroix** [museumsvictoria/nodel#74]
Keyboard shortcuts such as Shift + character appear to be disabled when entering information into the bindings.

**Comment by justparking** [comment]
Yeah, I've logged this too. It's a duplicate of #63. 

@mcartmel, I'm going to pull down the latest release and roll back all recent UI changes until this one is fixed.

**Comment by mcartmel** [comment]
No need, I've resolved this now.
