### ISSUE TITLE
Iboot Recipe

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel#75]
Just checking to see if the iboot recipe supports the newer iboot-GS.  The model appears to be functionally similar to the g2+ but also has a built in 2 port ethernet switch.

[iboot g2s](http://dataprobe.com/iboot-g2s/)

**Comment by scroix** [comment]
Hi Science World,

I can confirm the newer recipe works with the g2s, no extra configuration needed.

We use a bunch of them over at Museums Victoria. The extra Ethernet port is a pass through, which can be pretty handy.
