### ISSUE TITLE
uimodes - overflowed text has some rendering issues

### ISSUE THREAD

**Issue by scroix** [museumsvictoria/nodel#77]
_v2.1.1-feat_uimodes_rev223_

Just a bit of funky behaviour with actions on Firefox and Chrome when the text expands the container. It's nothing special on Firefox, but the video below for Chrome shows a bit of _tearing_ and a scroll bar.

![new_ui_actions_firefox](https://cloud.githubusercontent.com/assets/9277107/22192414/057868fe-e188-11e6-9470-2233a168d482.png)

_Also see video._
[new_ui_actions_chrome.zip](https://github.com/museumsvictoria/nodel/files/722679/new_ui_actions_chrome.zip)

**Comment by mcartmel** [comment]
Resolved in ui branch
