### ISSUE TITLE
Parameters Missing from AdamIO node on build 223

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel#79]
When editing the AdamIO node on nodel with build 2.1.1 rev 223 the parameters are not visible.  There is a parameters section, but no values/options/fields.

If I downgrade back to build 196 it works again.

**Comment by scroix** [comment]
Hi Scienceworld,

I had a look this morning, I've not got a solution for you, but I can confirm the same issue on my end when utilising the [Advantech ADAM 6060 relay module](https://github.com/museumsvictoria/nodel-recipes/tree/master/Advantech%20ADAM%206060%20relay%20module) recipe.

**-- Recipe running on r214**

![adam_r214](https://cloud.githubusercontent.com/assets/9277107/23186530/967b5e28-f8db-11e6-960d-29ce764c5b1e.png)

**-- Recipe running on r223**

![adam_r223](https://cloud.githubusercontent.com/assets/9277107/23186535/994f396c-f8db-11e6-91d2-1f805a016c87.png)

I'll have another look.

**Comment by scroix** [comment]
Okay!

I _think_ I found a solution, the parameter's hint wasn't handling the data type passed to it.

I've updated the recipe [here](https://github.com/museumsvictoria/nodel-recipes/tree/master/Advantech%20ADAM%206060%20relay%20module), give it a go, and let me know.

**Comment by scienceworld** [comment]
Yes, this worked! thank you.

**Comment by mcartmel** [comment]
Please note that this has now been resolved in #80
