### ISSUE TITLE
In node view, clicking Nodel logo could fill in previous node's name to aid navigation

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#86]
As per title, this could make browsing the nodel network a little easier instead of having to start from the root (blank search) every time.

For example, you've just finished look at Node called "Museum X Gallery Y Device Z". When you click on Nodel logo to browse other nodes, the browser should automatically have the node name filled in and the input box with focus. Pressing Backspace (or Ctrl-Backspace) would quickly jump up the loose hierarchy, as nodes in "Museum X Gallery Y", then "Museum X" would appear, etc.

Right now I'm finding it very very tedious having to continually fill in the search button when I'm jumping around the nodel network. This recommendation is as close to a simple solution I can think of without any major rework.

Unless others have better ideas, I think it's worth a trial.

(FYI @scroix)

**Comment by scroix** [comment]
Yes!

We've had this suggested as a QOL improvement by a couple of technicians. We're currently running just under 1,500 nodes so anything to improve navigation is appreciated.

An additional idea might be _tabbing_ from the search field to a found node, or the _enter_ key loading the top search entry. This removes the need to utilise the mouse after you've narrowed down your search to just one node.

**Comment by mcartmel** [comment]
Logo now links to the search page and sets its own node name as the initial search value. Added to feature_uimods branch.

**Comment by justparking** [comment]
This is a great improvement!

Any possibility of having a "back-button-like" (e.g. ⇤, ←, ↱, ⇐, etc.) mechanism to erase word-by-word (right to left) so you can "walk" up the tree. Otherwise you're left having to push Backspace several times (or Ctrl-Backspace, if you know the shortcut). Thought it'd be a simple addition with a lot of value.

**Comment by mcartmel** [comment]
Any precedent/convention that can be followed for this? (apart from ctrl-backspace).

**Comment by justparking** [comment]
There are many for formal trees like file-systems:

### Windows 10 Explorer:
_On much older versions of Windows, Backspace itself used to be "Up One Level" but its behaviour is now like the Browser Back Button which makes use of history instead. They now use Alt-Up Arrow instead._
![image](https://cloud.githubusercontent.com/assets/5266533/24702353/c05fe218-1a41-11e7-9ed1-2d71831c6e2f.png)

_Note: 

### Google Drive:
_This is obviously not intuitive._
![image](https://cloud.githubusercontent.com/assets/5266533/24702481/4264452e-1a42-11e7-9381-5fb65b5a7cb5.png)



Nodel has no explicit tree structure of course. It relies on a sensible node naming convention to create the illusion of a tree where new "branches" are almost always aligned along word-difference boundaries. It is a natural convention and most existing sites already employ this convention hence why I thought it'd make sense to simulate an "Up To..." using word backspace as a best-effort, though not always precise, solution.

I don't feeling strongly about the choice of "Up" or "Back" and related symbology, as long as whatever it is, makes it possible to walk the tree.

Ideally some code would be written to turn the flat namespace into a hierarchy so that precise tree walking could be done, but that's a non-trivial programming task and would impact far more areas of the code base.

**Comment by mcartmel** [comment]
Sure, but "ctrl-backspace" is pretty much the same as "alt-up" or "g p", so what kind of other shortcut do you think is better? You mean having an actual "←" button?

**Comment by justparking** [comment]
Yeah, was thinking that since you'd have your hand on the mouse (or finger on touch-screen / mobile) having a button/link/symbol to click/touch would be really convenient instead of having to jump to a keyboard.

**Comment by mcartmel** [comment]
Added 'erase last word' shortcut to node list/search page.
