### ISSUE TITLE
Absolute filter for nodeURLs 

### ISSUE THREAD

**Issue by mcartmel** [museumsvictoria/nodel#89]
Currently, the node actions/events lookup used in the bindings forms will use REST/nodeURLs to retrieve node location.

If you have node's called "abc" and "abcd", and you search for "abc" then nodeURLs will currently return two nodes, which means the autocomplete function will show the actions/events of two nodes.

It would be good to have an option to search for a specific node name.

**Comment by justparking** [comment]
Added `/nodeURLsForNode` in release rev251.
