### ISSUE TITLE
Basic file management for Node

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#90]
It's happening often that nodes are being created with several supporting files outside of just the `script.py` file itself. This presents a big hurdle in managing those files because that cannot be directly through the Nodel browser interface as it is just limited to `nodeConfig.json` and `script.py`.

There is now a REST end-point available in the latest [testing release](https://github.com/museumsvictoria/nodel/releases) which should facilitate that mechanism being added to the web-ui.

* **/%NODE%/REST/files/list** - lists all file paths and modified dates e.g. `[{"path":"content/index.xml", "modified":"2017-03-04T15:07:34.000+11:00"}, ...]`
* **/%NODE%/REST/files/contents?path=%PATH%** - returns the contents of the files
* **/%NODE%/REST/files/delete?path=%PATH%** - deletes the file
* **/%NODE%/REST/files/save?path=%PATH%** - saves contents to a file (creates if does not already exist) using HTTP POST data.

### CURL example:
`> curl http://10.1.1.12:8085/nodes/MyFrontEnd/REST/files/save?path=content/index.xml -v --data-binary @index.xml`

**Comment by justparking** [comment]
Related development branch: `feat_baseRecipes`

**Comment by mcartmel** [comment]
Added support for editing file types 'py','xml','js','json','html','htm','css','java','groovy','sql','sh'
