### ISSUE TITLE
Timers should not start if main() fails

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#94]
(as per title)

**Comment by scroix** [comment]
It's very similar, but the _stopped_ argument ought to prevent timers starting, even if their interval arguments had been set prior to main()

```
# currently
createTimer()...
            if (!stopped && delay > 0 || interval > 0) {
                timer.start();
```

The workaround for these sort of timers ( which begin later based on other conditions ) involves stopping timers _as part of_ main()

```
dwell = Timer(deactivate, DEFAULT_DWELL * 60)
def main(arg = None):
  dwell.stop()
  if param_dwell:
    dwell.setInterval(param_dwell * 60) # minutes-to-seconds
```

**Comment by justparking** [comment]
I just noticed that bug you pointed out in your first snippet of code! It was an OR / AND precedence bug that needed some brackets.

Anyway, that's fixed that and timer also don't start if there is an exception raised within any 'main' entry-points i.e. `def main()`, `@after_main` and `@before_main` related functions.
