### ISSUE TITLE
AdamIO 6060 concurrent command issue

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel#95]
We have an adam io with 5 relay outputs configured and are using an AdamIO nodel recipe.  We have 5 different Exhibit nodes configured to listen for events from one gallery.  Intermittently when all 5 of those exhibit nodes issues an on or off command concurrently one or more of the relays does not change state.

I believe this is an issue with possibly multithreading and having the modbus commands issued from the Nodel host too quickly in succession and reaching a concurrency limitation within the AdamIO.  I have added a 1 second pause before issuing the tcp send but have a feeling that might not help too much as if it is multi threaded instead of queued they all wait the same amount of time and still happen concurrently.

Let us know what you think.

**Comment by scroix** [comment]
We had a couple of issues with the ADAM6060 after moving to the new recipe driven by the Nodel toolkit. In our case, the devices would drop their connections after a period of overuse.

As a result @justparking put in a lot of effort to debug the recipe, and include some failsafes. The current version has been quite robust, and it sounds like we're using it in similar scenarios.

[Perhaps, you might find it helpful too!](https://gist.github.com/scroix/ce8c212957271a2febc299f8cc833f58)

It's designed for both the ADAM6050/6060. Just select the appropriate model in the parameters.

**Comment by scienceworld** [comment]
Thank you, this is newer than what we were running and have updated to this recipe.

How come this isnt in the main nodel recipe git repo?
I wonder if we could get the custom labels back for the relays as that was handy.

I'm going to try this for the next week and see if we have any issues.

**Comment by scroix** [comment]
We just hadn't gotten around to uploading that recipe, but I'll add it to the _alpha_ branch soon.

I agree about the labels. It'd be a good little project to port them from the exisiting recipe.

I'll be interested to hear if this recipe solves your issues.

**Comment by scienceworld** [comment]
This version of the recipe does resolve the issue.  Look forward to see it committed to the general repo

**Comment by scroix** [comment]
Great!

The recipe is sitting in the [alpha branch](https://github.com/museumsvictoria/nodel-recipes/tree/alpha) which is soon to be merged.
