### ISSUE TITLE
Formatting issues with new bindings layout

### ISSUE THREAD

**Issue by scroix** [museumsvictoria/nodel#97]
![calendar](https://cloud.githubusercontent.com/assets/9277107/24085717/df910e90-0d54-11e7-9f20-2aa3fb04372d.png)

Running on r282.

I reckon this has to do with the extra long names. Otherwise a great layout.

**Comment by mcartmel** [comment]
Resolved in 2d7bd60ee2c3fe87c3b6c13fc0c7d88460ca1ee3
